modules_rules = {
    "importlib.metadata": (None, (3, 8)),
    "test.support.bytecode_helper": (None, (3, 9)),
    "test.support.import_helper": (None, (3, 10)),
    "test.support.os_helper": (None, (3, 10)),
    "test.support.threading_helper": (None, (3, 10)),
    "test.support.warnings_helper": (None, (3, 10)),
}

classes_rules = {
    "argparse.BooleanOptionalAction": (None, (3, 9)),
    "contextlib.AsyncContextDecorator": (None, (3, 10)),
    "importlib.abc.TraversableResources": (None, (3, 9)),
    "importlib.metadata.EntryPoints": (None, (3, 10)),
    "types.GenericAlias": (None, (3, 9)),
    "typing.ForwardRef": (None, (3, 7)),
    "typing.ParamSpec": (None, (3, 10)),
    "xml.sax.handler.LexicalHandler": (None, (3, 10)),
}

exceptions_rules = {
    "EncodingWarning": (None, (3, 10)),
}

functions_rules = {
    "_thread.get_native_id": (None, (3, 8)),
    "abc.update_abstractmethods": (None, (3, 10)),
    "aiter": (None, (3, 10)),
    "anext": (None, (3, 10)),
    "base64.b32hexdecode": (None, (3, 10)),
    "base64.b32hexencode": (None, (3, 10)),
    "bdb.Breakpoint.clearBreakpoints": (None, (3, 10)),
    "codecs.unregister": (None, (3, 10)),
    "collections.Counter.total": (None, (3, 10)),
    "contextlib.aclosing": (None, (3, 10)),
    "curses.has_extended_color_support": (None, (3, 10)),
    "importlib.metadata.packages_distributions": (None, (3, 10)),
    "importlib.resources.as_file": (None, (3, 9)),
    "inspect.get_annotations": (None, (3, 10)),
    "int.bit_count": (None, (3, 10)),
    "io.text_encoding": (None, (3, 10)),
    "ipaddress.IPv4Address.__format__": (None, (3, 9)),
    "ipaddress.IPv6Address.__format__": (None, (3, 9)),
    "itertools.pairwise": (None, (3, 10)),
    "locale.localize": (None, (3, 10)),
    "logging.LoggerAdapter._log": (None, (3, 6)),
    "multiprocessing.get_start_method": (None, (3, 4)),
    "os.eventfd": (None, (3, 10)),
    "os.eventfd_read": (None, (3, 10)),
    "os.eventfd_write": (None, (3, 10)),
    "os.splice": (None, (3, 10)),
    "pathlib.Path.hardlink_to": (None, (3, 10)),
    "platform.freedesktop_os_release": (None, (3, 10)),
    "statistics.correlation": (None, (3, 10)),
    "statistics.covariance": (None, (3, 10)),
    "statistics.linear_regression": (None, (3, 10)),
    "symtable.Symbol.is_annotated": (None, (3, 6)),
    "sysconfig._get_preferred_schemes": (None, (3, 10)),
    "sysconfig.get_default_scheme": (None, (3, 10)),
    "sysconfig.get_preferred_scheme": (None, (3, 10)),
    "test.support.check_disallow_instantiation": (None, (3, 10)),
    "test.support.skip_if_broken_multiprocessing_synchronize": (None, (3, 10)),
    "threading.getprofile": (None, (3, 10)),
    "threading.gettrace": (None, (3, 10)),
    "typing.is_typeddict": (None, (3, 10)),
    "unittest.TestCase.assertNoLogs": (None, (3, 10)),
    "zipimport.zipimporter.create_module": (None, (3, 10)),
    "zipimport.zipimporter.exec_module": (None, (3, 10)),
    "zipimport.zipimporter.find_spec": (None, (3, 10)),
    "zipimport.zipimporter.invalidate_caches": (None, (3, 10)),
}

variables_and_constants_rules = {
    "AttributeError.name": (None, (3, 10)),
    "AttributeError.obj": (None, (3, 10)),
    "NameError.name": (None, (3, 10)),
    "OSError.filename2": (None, (3, 4)),
    "SyntaxError.end_lineno": (None, (3, 10)),
    "SyntaxError.end_offset": (None, (3, 10)),
    "_thread.TIMEOUT_MAX": (None, (3, 2)),
    "ast.PyCF_ALLOW_TOP_LEVEL_AWAIT": (None, (3, 8)),
    "ast.PyCF_TYPE_COMMENTS": (None, (3, 8)),
    "classmethod.__wrapped__": (None, (3, 10)),
    "dict.items.mapping": (None, (3, 10)),
    "dict.keys.mapping": (None, (3, 10)),
    "dict.values.mapping": (None, (3, 10)),
    "fcntl.F_GETPIPE_SZ": (None, (3, 10)),
    "fcntl.F_SETPIPE_SZ": (None, (3, 10)),
    "importlib.metadata.metadata.json": (None, (3, 10)),
    "logging.LoggerAdapter.manager": (None, (3, 6)),
    "mmap.MAP_POPULATE": (None, (3, 10)),
    "object.__match_args__": (None, (3, 10)),
    "os.EFD_CLOEXEC": (None, (3, 10)),
    "os.EFD_NONBLOCK": (None, (3, 10)),
    "os.EFD_SEMAPHORE": (None, (3, 10)),
    "os.O_EVTONLY": (None, (3, 10)),
    "os.O_FSYNC": (None, (3, 10)),
    "os.O_NOFOLLOW_ANY": (None, (3, 10)),
    "os.O_SYMLINK": (None, (3, 10)),
    "os.RWF_APPEND": (None, (3, 10)),
    "os.SPLICE_F_MORE": (None, (3, 10)),
    "os.SPLICE_F_MOVE": (None, (3, 10)),
    "os.SPLICE_F_NONBLOCK": (None, (3, 10)),
    "pyclbr.Class.end_lineno": (None, (3, 10)),
    "pyclbr.Function.end_lineno": (None, (3, 10)),
    "pyclbr.Function.is_async": (None, (3, 10)),
    "resource.RLIMIT_KQUEUES": (None, (3, 10)),
    "socket.IPPROTO_MPTCP": (None, (3, 10)),
    "socket.IP_RECVTOS": (None, (3, 10)),
    "socket.TCP_KEEPALIVE": (None, (3, 10)),
    "ssl.OP_IGNORE_UNEXPECTED_EOF": (None, (3, 10)),
    "ssl.SSLContext.security_level": (None, (3, 10)),
    "ssl.VERIFY_ALLOW_PROXY_CERTS": (None, (3, 10)),
    "ssl.VERIFY_X509_PARTIAL_CHAIN": (None, (3, 10)),
    "staticmethod.__wrapped__": (None, (3, 10)),
    "sys.orig_argv": (None, (3, 10)),
    "sys.stdlib_module_names": (None, (3, 10)),
    "threading.__excepthook__": (None, (3, 10)),
    "types.EllipsisType": ((2, 0), (3, 10)),
    "types.ModuleType.__spec__": (None, (3, 4)),
    "types.NoneType": ((2, 0), (3, 10)),
    "types.NotImplementedType": ((2, 0), (3, 10)),
    "types.UnionType": (None, (3, 10)),
    "typing.Concatenate": (None, (3, 10)),
    "typing.ParamSpecKwargs": (None, (3, 10)),
    "typing.TypeAlias": (None, (3, 10)),
    "typing.TypeGuard": (None, (3, 10)),
    "urllib.parse._UNSAFE_URL_BYTES_TO_REMOVE": (None, (3, 10)),
}

decorators_rules = {
}

kwargs_rules = {
    ("_thread.lock.acquire", "timeout"): (None, (3, 2)),
    ("bisect.bisect", "key"): (None, (3, 10)),
    ("bisect.bisect_left", "key"): (None, (3, 10)),
    ("bisect.bisect_right", "key"): (None, (3, 10)),
    ("bisect.insort", "key"): (None, (3, 10)),
    ("bisect.insort_left", "key"): (None, (3, 10)),
    ("bisect.insort_right", "key"): (None, (3, 10)),
    # 3.6.13+, 3.7.10+, 3.8.8+, 3.9.2+, 3.10+
    ("cgi.parse", "separator"): (None, (3, 6)),
    # 3.6.13+, 3.7.10+, 3.8.8+, 3.9.2+, 3.10+
    ("cgi.parse_multipart", "separator"): (None, (3, 6)),
    ("compile", "optimize"): (None, (3, 2)),
    ("dataclasses.dataclass", "kw_only"): (None, (3, 10)),
    ("dataclasses.dataclass", "match_args"): (None, (3, 10)),
    ("dataclasses.dataclass", "slots"): (None, (3, 10)),
    ("dataclasses.field", "kw_only"): (None, (3, 10)),
    ("fileinput.FileInput", "encoding"): (None, (3, 10)),
    ("fileinput.FileInput", "errors"): (None, (3, 10)),
    ("fileinput.hook_compressed", "encoding"): (None, (3, 10)),
    ("fileinput.hook_compressed", "errors"): (None, (3, 10)),
    ("fileinput.input", "encoding"): (None, (3, 10)),
    ("fileinput.input", "errors"): (None, (3, 10)),
    ("glob.glob", "dir_fd"): (None, (3, 10)),
    ("glob.glob", "root_dir"): (None, (3, 10)),
    ("glob.iglob", "dir_fd"): (None, (3, 10)),
    ("glob.iglob", "recursive"): (None, (3, 5)),
    ("glob.iglob", "root_dir"): (None, (3, 10)),
    ("http.server.SimpleHTTPRequestHandler", "directory"): (None, (3, 7)),
    ("inspect.Signature.from_callable", "globalns"): (None, (3, 10)),
    ("inspect.Signature.from_callable", "localns"): (None, (3, 10)),
    ("inspect.signature", "eval_str"): (None, (3, 10)),
    ("inspect.signature", "globals"): (None, (3, 10)),
    ("inspect.signature", "locals"): (None, (3, 10)),
    ("logging.Formatter", "defaults"): (None, (3, 10)),
    ("logging.config.fileConfig", "encoding"): (None, (3, 10)),
    ("os.path.realpath", "strict"): (None, (3, 10)),
    ("os.startfile", "arguments"): (None, (3, 10)),
    ("os.startfile", "cwd"): (None, (3, 10)),
    ("os.startfile", "show_cmd"): (None, (3, 10)),
    ("pathlib.Path.chmod", "follow_symlinks"): (None, (3, 10)),
    ("pathlib.Path.stat", "follow_symlinks"): (None, (3, 10)),
    ("pathlib.Path.write_text", "newline"): (None, (3, 10)),
    ("pprint.PrettyPrinter", "underscore_numbers"): (None, (3, 10)),
    ("pprint.pformat", "underscore_numbers"): (None, (3, 10)),
    ("pprint.pprint", "underscore_numbers"): (None, (3, 10)),
    ("pyclbr.Class", "end_lineno"): (None, (3, 10)),
    ("pyclbr.Function", "end_lineno"): (None, (3, 10)),
    ("pyclbr.Function", "is_async"): (None, (3, 10)),
    ("smtplib.LMTP", "timeout"): (None, (3, 9)),
    ("ssl.get_server_certificate", "timeout"): (None, (3, 10)),
    ("statistics.harmonic_mean", "weights"): (None, (3, 10)),
    ("subprocess.Popen", "pipesize"): (None, (3, 10)),
    ("subprocess.call", "pipesize"): (None, (3, 10)),
    ("subprocess.check_call", "pipesize"): (None, (3, 10)),
    ("subprocess.check_output", "pipesize"): (None, (3, 10)),
    ("subprocess.run", "pipesize"): (None, (3, 10)),
    ("tempfile.TemporaryDirectory", "ignore_cleanup_errors"): (None, (3, 10)),
    ("tkinter.font.nametofont", "root"): (None, (3, 10)),
    ("traceback.TracebackException", "compact"): (None, (3, 10)),
    # 3.6.8+, 3.7.2+, 3.8+
    ("urllib.parse.parse_qs", "max_num_fields"): (None, (3, 6)),
    # 3.6.13+, 3.7.10+, 3.8.8+, 3.9.2+, 3.10+
    ("urllib.parse.parse_qs", "separator"): (None, (3, 6)),
    # 3.6.8+, 3.7.2+, 3.8+
    ("urllib.parse.parse_qsl", "max_num_fields"): (None, (3, 6)),
    # 3.6.13+, 3.7.10+, 3.8.8+, 3.9.2+, 3.10+
    ("urllib.parse.parse_qsl", "separator"): (None, (3, 6)),
    ("venv.create", "upgrade_deps"): (None, (3, 9)),
    ("xml.dom.minidom.Node.toprettyxml", "standalone"): (None, (3, 9)),
    ("xml.dom.minidom.Node.toxml", "standalone"): (None, (3, 9)),
    ("xml.dom.minidom.Node.writexml", "standalone"): (None, (3, 9)),
    ("zip", "strict"): (None, (3, 10)),
}
