modules_rules = {
    "graphlib": (None, (3, 9)),
    "test.support.socket_helper": (None, (3, 9)),
    "zoneinfo": (None, (3, 9)),
}

classes_rules = {
    "asyncio.BufferedProtocol": (None, (3, 7)),
    "asyncio.PidfdChildWatcher": (None, (3, 9)),
    "importlib.abc.Traversable": (None, (3, 9)),
    "importlib.abc.TraversableReader": (None, (3, 9)),
    "pstats.FunctionProfile": (None, (3, 9)),
    "pstats.StatsProfile": (None, (3, 9)),
}

exceptions_rules = {
}

functions_rules = {
    "ast.unparse": (None, (3, 9)),
    "asyncio.loop.shutdown_default_executor": (None, (3, 9)),
    "asyncio.to_thread": (None, (3, 9)),
    "bytearray.removeprefix": (None, (3, 9)),
    "bytearray.removesuffix": (None, (3, 9)),
    "bytes.removeprefix": (None, (3, 9)),
    "bytes.removesuffix": (None, (3, 9)),
    "curses.get_escdelay": (None, (3, 9)),
    "curses.get_tabsize": (None, (3, 9)),
    "curses.set_escdelay": (None, (3, 9)),
    "curses.set_tabsize": (None, (3, 9)),
    "gc.is_finalized": (None, (3, 9)),
    "imaplib.IMAP4.unselect": (None, (3, 9)),
    "importlib.machinery.FrozenImporter.create_module": (None, (3, 4)),
    "importlib.machinery.FrozenImporter.exec_module": (None, (3, 4)),
    "importlib.resources.files": (None, (3, 9)),
    "keyword.issoftkeyword": (None, (3, 9)),
    "logging.StreamHandler.setStream": (None, (3, 7)),
    "math.lcm": (None, (3, 9)),
    "math.nextafter": (None, (3, 9)),
    "math.ulp": (None, (3, 9)),
    "multiprocessing.SimpleQueue.close": (None, (3, 9)),
    "os.pidfd_open": (None, (3, 9)),
    "os.waitstatus_to_exitcode": (None, (3, 9)),
    "pathlib.Path.link_to": (None, (3, 8)),
    "pathlib.Path.readlink": (None, (3, 9)),
    "pathlib.PurePath.is_relative_to": (None, (3, 9)),
    "pathlib.PurePath.with_stem": (None, (3, 9)),
    "pkgutil.resolve_name": (None, (3, 9)),
    "pstats.Stats.get_stats_profile": (None, (3, 9)),
    "random.randbytes": (None, (3, 9)),
    "signal.pidfd_send_signal": (None, (3, 9)),
    "socket.socket.recv_fds": (None, (3, 9)),
    "socket.socket.send_fds": (None, (3, 9)),
    "statistics.NormalDist.zscore": (None, (3, 9)),
    "str.removeprefix": (None, (3, 9)),
    "str.removesuffix": (None, (3, 9)),
    "test.support.print_warning": (None, (3, 9)),
    "test.support.wait_process": (None, (3, 9)),
    "tracemalloc.reset_peak": (None, (3, 9)),
    "types.CodeType.replace": (None, (3, 8)),
    "typing.get_origin": (None, (3, 8)),
    "venv.EnvBuilder.upgrade_dependencies": (None, (3, 9)),
    "xml.etree.ElementTree.indent": (None, (3, 9)),
}

variables_and_constants_rules = {
    "decimal.HAVE_CONTEXTVAR": (None, (3, 7)),
    "difflib.SequenceMatcher.bjunk": (None, (3, 2)),
    "difflib.SequenceMatcher.bpopular": (None, (3, 2)),
    "fcntl.F_GETPATH": (None, (3, 9)),
    "fcntl.F_OFD_GETLK": (None, (3, 9)),
    "fcntl.F_OFD_SETLK": (None, (3, 9)),
    "fcntl.F_OFD_SETLKW": (None, (3, 9)),
    "http.HTTPStatus.EARLY_HINTS": (None, (3, 9)),
    "http.HTTPStatus.IM_A_TEAPOT": (None, (3, 9)),
    "http.HTTPStatus.TOO_EARLY": (None, (3, 9)),
    "keyword.softkwlist": (None, (3, 9)),
    "logging.StreamHandler.terminator": (None, (3, 2)),
    "os.CLD_KILLED": (None, (3, 9)),
    "os.CLD_STOPPED": (None, (3, 9)),
    "os.P_PIDFD": (None, (3, 9)),
    "socket.CAN_J1939": (None, (3, 9)),
    "socket.CAN_RAW_JOIN_FILTERS": (None, (3, 9)),
    "socket.IPPROTO_UDPLITE": (None, (3, 9)),
    "sys.__unraisablehook__": (None, (3, 8)),
    "sys.flags.dev_mode": (None, (3, 7)),
    "sys.flags.utf8_mode": (None, (3, 7)),
    "sys.platlibdir": (None, (3, 9)),
    "time.CLOCK_TAI": (None, (3, 9)),
    "token.COLONEQUAL": (None, (3, 8)),
    "token.TYPE_COMMENT": (None, (3, 8)),
    "token.TYPE_IGNORE": (None, (3, 8)),
    "tracemalloc.Traceback.total_nframe": (None, (3, 9)),
    "typing.Annotated": (None, (3, 9)),
    "unittest.mock.Mock.call_args.args": (None, (3, 8)),
    "unittest.mock.Mock.call_args.kwargs": (None, (3, 8)),
    "urllib.response.addinfourl.status": (None, (3, 9)),
}

decorators_rules = {
    "functools.cache": (None, (3, 9)),
}

kwargs_rules = {
    ("argparse.ArgumentParser", "exit_on_error"): (None, (3, 9)),
    ("ast.dump", "indent"): (None, (3, 9)),
    ("asyncio.Future.cancel", "msg"): (None, (3, 9)),
    ("asyncio.Task.cancel", "msg"): (None, (3, 9)),
    ("asyncio.loop.create_connection", "happy_eyeballs_delay"): (None, (3, 8)),
    ("asyncio.loop.create_connection", "interleave"): (None, (3, 8)),
    ("bytearray.hex", "bytes_per_sep"): (None, (3, 8)),
    ("bytearray.hex", "sep"): (None, (3, 8)),
    ("compileall.compile_dir", "hardlink_dupes"): (None, (3, 9)),
    ("compileall.compile_dir", "limit_sl_dest"): (None, (3, 9)),
    ("compileall.compile_dir", "prependdir"): (None, (3, 9)),
    ("compileall.compile_dir", "stripdir"): (None, (3, 9)),
    ("compileall.compile_file", "hardlink_dupes"): (None, (3, 9)),
    ("compileall.compile_file", "limit_sl_dest"): (None, (3, 9)),
    ("compileall.compile_file", "prependdir"): (None, (3, 9)),
    ("compileall.compile_file", "stripdir"): (None, (3, 9)),
    ("concurrent.futures.Executor.shutdown", "cancel_futures"): (None, (3, 9)),
    ("ftplib.FTP", "encoding"): (None, (3, 9)),
    ("ftplib.FTP_TLS", "encoding"): (None, (3, 9)),
    ("hashlib.blake2b", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.blake2s", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.md5", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.new", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.sha1", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.sha224", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.sha256", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.sha384", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.sha3_224", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.sha3_256", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.sha3_384", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.sha3_512", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.sha512", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.shake_128", "usedforsecurity"): (None, (3, 9)),
    ("hashlib.shake_2", "usedforsecurity"): (None, (3, 9)),
    ("imaplib.IMAP4", "timeout"): (None, (3, 9)),
    ("imaplib.IMAP4.open", "timeout"): (None, (3, 9)),
    ("imaplib.IMAP4_SSL", "ssl_context"): (None, (3, 3)),
    ("imaplib.IMAP4_SSL", "timeout"): (None, (3, 9)),
    ("logging.basicConfig", "encoding"): (None, (3, 9)),
    ("logging.basicConfig", "errors"): (None, (3, 9)),
    ("logging.handlers.RotatingFileHandler", "errors"): (None, (3, 9)),
    ("logging.handlers.TimedRotatingFileHandler", "errors"): (None, (3, 9)),
    ("logging.handlers.WatchedFileHandler", "errors"): (None, (3, 9)),
    ("memoryview.hex", "bytes_per_sep"): (None, (3, 8)),
    ("memoryview.hex", "sep"): (None, (3, 8)),
    ("os.sendfile", "in_fd"): (None, (3, 9)),
    ("os.sendfile", "out_fd"): (None, (3, 9)),
    ("pow", "base"): (None, (3, 8)),
    ("pow", "exp"): (None, (3, 8)),
    ("pow", "mod"): (None, (3, 8)),
    ("random.sample", "counts"): (None, (3, 9)),
    ("smtplib.LMTP", "timeout"): (None, (3, 9)),
    ("subprocess.Popen", "extra_groups"): (None, (3, 9)),
    ("subprocess.Popen", "group"): (None, (3, 9)),
    ("subprocess.Popen", "umask"): (None, (3, 9)),
    ("subprocess.Popen", "user"): (None, (3, 9)),
    ("threading.Semaphore.release", "n"): (None, (3, 9)),
    ("typing.get_type_hints", "include_extras"): (None, (3, 9)),
    ("venv.EnvBuilder", "upgrade_deps"): (None, (3, 9)),
    ("xml.etree.ElementTree.xml.etree.ElementInclude.include", "base_url"): (None, (3, 9)),
    ("xml.etree.ElementTree.xml.etree.ElementInclude.include", "max_depth"): (None, (3, 9)),
}
